'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SVModel
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SVModel.IModelo")>  _
    Public Interface IModelo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IModelo/Reset", ReplyAction:="http://tempuri.org/IModelo/ResetResponse")>  _
        Sub Reset(ByVal IdModPozo As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IModelo/Reset", ReplyAction:="http://tempuri.org/IModelo/ResetResponse")>  _
        Function ResetAsync(ByVal IdModPozo As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IModelo/Delete", ReplyAction:="http://tempuri.org/IModelo/DeleteResponse")>  _
        Sub Delete(ByVal IdModPozo As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IModelo/Delete", ReplyAction:="http://tempuri.org/IModelo/DeleteResponse")>  _
        Function DeleteAsync(ByVal IdModPozo As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IModelo/Execute", ReplyAction:="http://tempuri.org/IModelo/ExecuteResponse")>  _
        Sub Execute(ByVal IdModPozo As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IModelo/Execute", ReplyAction:="http://tempuri.org/IModelo/ExecuteResponse")>  _
        Function ExecuteAsync(ByVal IdModPozo As String) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IModeloChannel
        Inherits SVModel.IModelo, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ModeloClient
        Inherits System.ServiceModel.ClientBase(Of SVModel.IModelo)
        Implements SVModel.IModelo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Reset(ByVal IdModPozo As String) Implements SVModel.IModelo.Reset
            MyBase.Channel.Reset(IdModPozo)
        End Sub
        
        Public Function ResetAsync(ByVal IdModPozo As String) As System.Threading.Tasks.Task Implements SVModel.IModelo.ResetAsync
            Return MyBase.Channel.ResetAsync(IdModPozo)
        End Function
        
        Public Sub Delete(ByVal IdModPozo As String) Implements SVModel.IModelo.Delete
            MyBase.Channel.Delete(IdModPozo)
        End Sub
        
        Public Function DeleteAsync(ByVal IdModPozo As String) As System.Threading.Tasks.Task Implements SVModel.IModelo.DeleteAsync
            Return MyBase.Channel.DeleteAsync(IdModPozo)
        End Function
        
        Public Sub Execute(ByVal IdModPozo As String) Implements SVModel.IModelo.Execute
            MyBase.Channel.Execute(IdModPozo)
        End Sub
        
        Public Function ExecuteAsync(ByVal IdModPozo As String) As System.Threading.Tasks.Task Implements SVModel.IModelo.ExecuteAsync
            Return MyBase.Channel.ExecuteAsync(IdModPozo)
        End Function
    End Class
End Namespace
