'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AGUJERO
    Public Property IDAGUJERO As String
    Public Property IDPOZO As String
    Public Property IDCATCLASIFAGUJERO As String
    Public Property NUMERO As Integer
    Public Property ADITEP As String
    Public Property PROFUNDIDADMD As Nullable(Of Double)
    Public Property COORDENADAX As Nullable(Of Double)
    Public Property COORDENADAY As Nullable(Of Double)
    Public Property COMENTARIO As String
    Public Property FECHAAPERTURA As Date
    Public Property FECHACIERRE As Date
    Public Property ENDRECORD As String

    Public Overridable Property POZO As POZO
    Public Overridable Property CONFIGURACION_ADMINISTRADOR As ICollection(Of CONFIGURACION_ADMINISTRADOR) = New HashSet(Of CONFIGURACION_ADMINISTRADOR)
    Public Overridable Property MOD_POZO As ICollection(Of MOD_POZO) = New HashSet(Of MOD_POZO)
    Public Overridable Property MOD_POZO_TUBERIA As ICollection(Of MOD_POZO_TUBERIA) = New HashSet(Of MOD_POZO_TUBERIA)

End Class
