'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BOMBA
    Public Property IDBOMBA As String
    Public Property IDFABRICANTE As String
    Public Property MODELO As String
    Public Property MED_PULGADAS As Double
    Public Property FRECUENCIAHZ As Double
    Public Property ETAPAS As Double
    Public Property MIN_RAN_OP As Double
    Public Property MAX_RAN_OP As Double
    Public Property MEJOR_EFICIENCIA As Double
    Public Property IDMOD_POZO As String
    Public Property RAIZ As Double

    Public Overridable Property COEFICIENTES As ICollection(Of COEFICIENTES) = New HashSet(Of COEFICIENTES)
    Public Overridable Property CAT_FABRICANTE As CAT_FABRICANTE
    Public Overridable Property MOD_POZO As MOD_POZO

End Class
