'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_CORRELACION
    Public Property IDCATCORRELACION As String
    Public Property NOMBRE As String
    Public Property NUM As Integer
    Public Property ENDRECORD As String

    Public Overridable Property CORRELACION As ICollection(Of CORRELACION) = New HashSet(Of CORRELACION)

End Class
