'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_TIPO_TUBERIA
    Public Property IDTIPOTUBERIA As String
    Public Property NOMBRE As String
    Public Property NUMERO As Integer
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO_TUBERIA As ICollection(Of MOD_POZO_TUBERIA) = New HashSet(Of MOD_POZO_TUBERIA)

End Class
