'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_MOD_POZO_QUICK
    Public Property IDCATMODPOZOQUICK As String
    Public Property NOMBRE As String
    Public Property NUM As Integer
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO_QUICK_GEN As ICollection(Of MOD_POZO_QUICK_GEN) = New HashSet(Of MOD_POZO_QUICK_GEN)

End Class
