'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CAT_FABRICANTE
    Public Property IDFABRICANTE As String
    Public Property NOMBRE As String

    Public Overridable Property BOMBA As ICollection(Of BOMBA) = New HashSet(Of BOMBA)

End Class
