'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COEFICIENTES
    Public Property IDDETALLE_BOMBA As String
    Public Property IDBOMBA As String
    Public Property COEFICIENTE1 As Double
    Public Property COEFICIENTE2 As Double
    Public Property COEFICIENTE3 As Double
    Public Property COEFICIENTE4 As Double
    Public Property COEFICIENTE5 As Double
    Public Property COEFICIENTE6 As Double
    Public Property IDDIVISION As String

    Public Overridable Property BOMBA As BOMBA
    Public Overridable Property CURVA_CARGA As ICollection(Of CURVA_CARGA) = New HashSet(Of CURVA_CARGA)
    Public Overridable Property DIVISIONES_COEFICIENTES As DIVISIONES_COEFICIENTES

End Class
