'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COMPORTAMIENTO_GASBN
    Public Property IDGASBN As String
    Public Property IDMODPOZO As String
    Public Property QLIQ As Double
    Public Property QGI As Double
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO

End Class
