'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONFIGURACION_ADMINISTRADOR
    Public Property IDCONFIGURACION As String
    Public Property IDAGUJERO As String
    Public Property FECHA_PROGRAMACION As Date
    Public Property MAXREINTENTOS As Integer
    Public Property IDUSUARIO As String
    Public Property FECHA_REGLA As Nullable(Of Date)
    Public Property IDMODPOZO As String

    Public Overridable Property AGUJERO As AGUJERO
    Public Overridable Property MOD_POZO As MOD_POZO
    Public Overridable Property EJECUCION_PROCESOS As ICollection(Of EJECUCION_PROCESOS) = New HashSet(Of EJECUCION_PROCESOS)

End Class
