'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CORRELACION_OPTIMA
    Public Property IDCORRELACIONOPTIMA As String
    Public Property IDCORRELACION As String
    Public Property PARAMETRO1 As Double
    Public Property PARAMETRO2 As Double
    Public Property DESVEST As Double
    Public Property ENDRECORD As String

    Public Overridable Property CORRELACION As CORRELACION

End Class
