'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CORRELACION_GENERAL
    Public Property IDCORRELACIONGENERAL As String
    Public Property IDCORRELACION As String
    Public Property ETIQUETA As String
    Public Property PROFMD As Double
    Public Property PROFMV As Nullable(Of Double)
    Public Property PRES As Double
    Public Property TEMP As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property CORRELACION As CORRELACION

End Class
