'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CORRELACION
    Public Property IDCORRELACION As String
    Public Property IDMODPOZO As String
    Public Property IDCATCORRELACION As String
    Public Property PWFCALCULADA As Nullable(Of Double)
    Public Property DIFPRESION As Nullable(Of Double)
    Public Property IPR As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property CAT_CORRELACION As CAT_CORRELACION
    Public Overridable Property CORRELACION_GENERAL As ICollection(Of CORRELACION_GENERAL) = New HashSet(Of CORRELACION_GENERAL)
    Public Overridable Property MOD_POZO As MOD_POZO
    Public Overridable Property CORRELACION_OPTIMA As ICollection(Of CORRELACION_OPTIMA) = New HashSet(Of CORRELACION_OPTIMA)

End Class
