'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CURVA_CARGA
    Public Property IDFRECUENCIA As String
    Public Property GASTOLIQUIDO As Double
    Public Property CARGA As Double
    Public Property IDDETALLE_BOMBA As String
    Public Property REGRESION As Nullable(Of Double)

    Public Overridable Property COEFICIENTES As COEFICIENTES

End Class
