'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EJECUCION_PROCESOS
    Public Property IDEJECUCION As String
    Public Property IDCONFIGURACION As String
    Public Property ESTATUS As Boolean
    Public Property NUM_REINTENTOS As Integer
    Public Property FECHA_INICIO As Date
    Public Property FECHA_FINAL As Nullable(Of Date)

    Public Overridable Property CONFIGURACION_ADMINISTRADOR As CONFIGURACION_ADMINISTRADOR

End Class
