'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IPR_GENERAL
    Public Property IDIPRGENERAL As String
    Public Property IDIPR As String
    Public Property QL As Double
    Public Property QO As Double
    Public Property PWF As Double
    Public Property ENDRECORD As String

    Public Overridable Property IPR As IPR

End Class
