'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO_TRAYEC
    Public Property IDMODPOZOTRAYEC As String
    Public Property IDMODPOZO As String
    Public Property PROFUNDIDADMD As Double
    Public Property PROFUNDIDADMV As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO

End Class
