'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO_QUICK_GEN
    Public Property IDMODPOZOQUICKGEN As String
    Public Property IDMODPOZOQUICK As String
    Public Property IDCATMODPOZOQUICK As String
    Public Property ETIQUETA As String
    Public Property PROFMD As Double
    Public Property PROFMV As Nullable(Of Double)
    Public Property PRESION As Double
    Public Property TEMP As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property CAT_MOD_POZO_QUICK As CAT_MOD_POZO_QUICK
    Public Overridable Property MOD_POZO_QUICK As MOD_POZO_QUICK

End Class
