'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO_BNC
    Public Property IDMODPOZOBNC As Long
    Public Property ENTRY As Nullable(Of Double)
    Public Property METHOD As Nullable(Of Double)
    Public Property CO2 As Nullable(Of Double)
    Public Property N2 As Nullable(Of Double)
    Public Property GLRINY As Nullable(Of Double)
    Public Property GLRATE As Nullable(Of Double)
    Public Property VALVEDEPTH As Nullable(Of Double)
    Public Property DIAMVAL As Nullable(Of Double)
    Public Property QGIMIN As Nullable(Of Double)
    Public Property QGIMAX As Nullable(Of Double)
    Public Property IDMODPOZO As String
    Public Property GRAVITY As Nullable(Of Double)
    Public Property H2S As Nullable(Of Double)
    Public Property RANGESYSTEM As Nullable(Of Double)

    Public Overridable Property MOD_POZO As MOD_POZO

End Class
