'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO
    Public Property IDMODPOZO As String
    Public Property IDAGUJERO As String
    Public Property FECHAEDOMECINI As Nullable(Of Date)
    Public Property FECHAEDOMECFIN As Nullable(Of Date)
    Public Property FECHAMODELO As Nullable(Of Date)
    Public Property OBSERVACIONES As String
    Public Property ENDRECORD As String

    Public Overridable Property AGUJERO As AGUJERO
    Public Overridable Property COMPORTAMIENTO_GASBN As ICollection(Of COMPORTAMIENTO_GASBN) = New HashSet(Of COMPORTAMIENTO_GASBN)
    Public Overridable Property CONFIGURACION_ADMINISTRADOR As ICollection(Of CONFIGURACION_ADMINISTRADOR) = New HashSet(Of CONFIGURACION_ADMINISTRADOR)
    Public Overridable Property CORRELACION As ICollection(Of CORRELACION) = New HashSet(Of CORRELACION)
    Public Overridable Property IPR As ICollection(Of IPR) = New HashSet(Of IPR)
    Public Overridable Property MOD_POZO_BEC As ICollection(Of MOD_POZO_BEC) = New HashSet(Of MOD_POZO_BEC)
    Public Overridable Property MOD_POZO_GENERAL As ICollection(Of MOD_POZO_GENERAL) = New HashSet(Of MOD_POZO_GENERAL)
    Public Overridable Property MOD_POZO_QUICK As ICollection(Of MOD_POZO_QUICK) = New HashSet(Of MOD_POZO_QUICK)
    Public Overridable Property MOD_POZO_TEMP As ICollection(Of MOD_POZO_TEMP) = New HashSet(Of MOD_POZO_TEMP)
    Public Overridable Property MOD_POZO_TRAYEC As ICollection(Of MOD_POZO_TRAYEC) = New HashSet(Of MOD_POZO_TRAYEC)
    Public Overridable Property PRODUCTIVIDAD As ICollection(Of PRODUCTIVIDAD) = New HashSet(Of PRODUCTIVIDAD)
    Public Overridable Property VLP_IPR_GASTO_INYECCION As ICollection(Of VLP_IPR_GASTO_INYECCION) = New HashSet(Of VLP_IPR_GASTO_INYECCION)
    Public Overridable Property VLP_IPR As ICollection(Of VLP_IPR) = New HashSet(Of VLP_IPR)
    Public Overridable Property BOMBA As ICollection(Of BOMBA) = New HashSet(Of BOMBA)
    Public Overridable Property MOD_POZO_BNC As ICollection(Of MOD_POZO_BNC) = New HashSet(Of MOD_POZO_BNC)

End Class
