'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO_GENERAL
    Public Property IDMODPOZOGENERAL As String
    Public Property IDMODPOZO As String
    Public Property FLUID As Nullable(Of Double)
    Public Property PVTMODEL As Nullable(Of Double)
    Public Property SEPARATOR As Nullable(Of Double)
    Public Property EMULSION As Nullable(Of Double)
    Public Property HYDRATE As Nullable(Of Double)
    Public Property WATVIS As Nullable(Of Double)
    Public Property VISMOD As Nullable(Of Double)
    Public Property FLOWTYPE As Nullable(Of Double)
    Public Property WELLTYPE As Nullable(Of Double)
    Public Property LIFTMETHOD As Nullable(Of Double)
    Public Property LIFTYPE As Nullable(Of Double)
    Public Property PREDICT As Nullable(Of Double)
    Public Property TEMPMODEL As Nullable(Of Double)
    Public Property RANGESYSTEM As Nullable(Of Double)
    Public Property OUTPUTRES As Nullable(Of Double)
    Public Property COMPLETION As Nullable(Of Double)
    Public Property GRAVELPACK As Nullable(Of Double)
    Public Property INFLOWTYPE As Nullable(Of Double)
    Public Property GASCONING As Nullable(Of Double)
    Public Property COMPANY As String
    Public Property FIELD As String
    Public Property LOCATIONS As String
    Public Property WELL As String
    Public Property PLATAFORM As String
    Public Property ANALYST As String
    Public Property DATGENDATE As Nullable(Of Date)
    Public Property COMENTA As String
    Public Property IPRMETHOD As Nullable(Of Double)
    Public Property PRES As Nullable(Of Double)
    Public Property TRES As Nullable(Of Double)
    Public Property WC As Nullable(Of Double)
    Public Property TOTGOR As Nullable(Of Double)
    Public Property COMPACT As Nullable(Of Double)
    Public Property IRElK As Nullable(Of Double)
    Public Property QTEST As Nullable(Of Double)
    Public Property PTEST As Nullable(Of Double)
    Public Property MGSKINMETHOD As Nullable(Of Double)
    Public Property MGSKINMODEL As Nullable(Of Integer)
    Public Property RESPERM As Nullable(Of Double)
    Public Property THICKNESS As Nullable(Of Double)
    Public Property DRAINAGE As Nullable(Of Double)
    Public Property DIETZ As Nullable(Of Double)
    Public Property WBR As Nullable(Of Double)
    Public Property SKIN As Nullable(Of Double)
    Public Property ENTRY As Nullable(Of Double)
    Public Property METHOD As Nullable(Of Double)
    Public Property GRAVITY As Nullable(Of Double)
    Public Property H2S As Nullable(Of Double)
    Public Property CO2 As Nullable(Of Double)
    Public Property N2 As Nullable(Of Double)
    Public Property GLRINY As Nullable(Of Double)
    Public Property GLRATE As Nullable(Of Double)
    Public Property VALVEDEPTH As Nullable(Of Double)
    Public Property DIAMVALBNC As Nullable(Of Double)
    Public Property HTC As Nullable(Of Double)
    Public Property THPD As Nullable(Of Double)
    Public Property THTD As Nullable(Of Double)
    Public Property RGATOTALAFORO As Nullable(Of Double)
    Public Property TRPRES As Nullable(Of Double)
    Public Property QGINYMIN As Nullable(Of Double)
    Public Property QGINYMAX As Nullable(Of Double)
    Public Property THTE As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO

End Class
