'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO_BEC
    Public Property IDMODPOZOBEC As String
    Public Property IDMODPOZO As String
    Public Property FRECMIN As Nullable(Of Double)
    Public Property FRECMAX As Nullable(Of Double)
    Public Property PROF_BEC As Nullable(Of Double)
    Public Property FREC_BEC As Nullable(Of Double)
    Public Property ODMAX_BEC As Nullable(Of Double)
    Public Property LONGCABLE_BEC As Nullable(Of Double)
    Public Property EFISEPGAS_BEC As Nullable(Of Double)
    Public Property ETAPAS_BEC As Nullable(Of Double)
    Public Property VOLTSUP_BEC As Nullable(Of Double)
    Public Property DESGASTE_BEC As Nullable(Of Double)
    Public Property REDUCGAS_BEC As Nullable(Of Double)
    Public Property BOMBA_BEC As Nullable(Of Double)
    Public Property MOTOR_BEC As Nullable(Of Double)
    Public Property POTENCIAMOTOR_BEC As Nullable(Of Double)
    Public Property CABLE_BEC As Nullable(Of Double)
    Public Property PRESUC_BEC As Nullable(Of Double)
    Public Property CORRIENTE_BEC As Nullable(Of Double)
    Public Property POTENCIA_BEC As Nullable(Of Double)
    Public Property PREDES_BEC As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO

End Class
