'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MOD_POZO_QUICK
    Public Property IDMODPOZOQUICK As String
    Public Property IDMODPOZO As String
    Public Property PROFVALVINY As Nullable(Of Double)
    Public Property PRESPROFVALV As Nullable(Of Double)
    Public Property TEMPPROFVALV As Nullable(Of Double)
    Public Property RELACIONGASACEITE As Nullable(Of Double)
    Public Property GORLIBRE As Nullable(Of Double)
    Public Property DELTAPVALV As Nullable(Of Double)
    Public Property PRESTRTEORICASUPERF As Nullable(Of Double)
    Public Property DELTAPYACIM As Nullable(Of Double)
    Public Property INDICEPROD As Nullable(Of Double)
    Public Property GASTOGCRITICO As Nullable(Of Double)
    Public Property PORCENGASTOGCRITIC0 As Nullable(Of Double)
    Public Property COEFTRANSFCALOR As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO
    Public Overridable Property MOD_POZO_QUICK_GEN As ICollection(Of MOD_POZO_QUICK_GEN) = New HashSet(Of MOD_POZO_QUICK_GEN)

End Class
