'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTIVIDAD_DETALLE
    Public Property IDPRODUCTIVIDADDETALLE As String
    Public Property IDPRODUCTIVIDAD As String
    Public Property QLIQ_RES1 As Double
    Public Property ENDRECORD As String

    Public Overridable Property PRODUCTIVIDAD As PRODUCTIVIDAD

End Class
