'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VLP_IPR_DETALLE
    Public Property IDVLPIPRDETALLE As String
    Public Property IDVLPIPR As String
    Public Property QL As Double
    Public Property QO As Double
    Public Property PWFVLP As Double
    Public Property PWFIPR As Double
    Public Property ENDRECORD As String

    Public Overridable Property VLP_IPR As VLP_IPR

End Class
