'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VLP_IPR_GASTO_INYECCION
    Public Property IDVLPIPRGASTOINYECCION As String
    Public Property IDMODPOZO As String
    Public Property QGI As Nullable(Of Double)
    Public Property QL As Nullable(Of Double)
    Public Property QG As Nullable(Of Double)
    Public Property QO As Nullable(Of Double)
    Public Property QW As Nullable(Of Double)
    Public Property PWFPTOSOL As Nullable(Of Double)
    Public Property PTH As Nullable(Of Double)
    Public Property TTH As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO
    Public Overridable Property VLP_IPR_GASTO_DETALLE As ICollection(Of VLP_IPR_GASTO_DETALLE) = New HashSet(Of VLP_IPR_GASTO_DETALLE)

End Class
