'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VLP_IPR
    Public Property IDVLPIPR As String
    Public Property IDMODPOZO As String
    Public Property PRODPTOSOL As Nullable(Of Double)
    Public Property PWFPTOSOL As Nullable(Of Double)
    Public Property PRODAFORO As Nullable(Of Double)
    Public Property PWFPRODAFORO As Nullable(Of Double)
    Public Property TITULO1 As String
    Public Property TITULO2 As String
    Public Property ENDRECORD As String

    Public Overridable Property MOD_POZO As MOD_POZO
    Public Overridable Property VLP_IPR_DETALLE As ICollection(Of VLP_IPR_DETALLE) = New HashSet(Of VLP_IPR_DETALLE)

End Class
