'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VLP_IPR_GASTO_DETALLE
    Public Property IDVLPIPRGASTODETALLE As String
    Public Property IDVLPIPRGASTOINYECCION As String
    Public Property PWFVLP As Double
    Public Property PWFIPR As Double
    Public Property TITULO As Nullable(Of Double)
    Public Property ENDRECORD As String

    Public Overridable Property VLP_IPR_GASTO_INYECCION As VLP_IPR_GASTO_INYECCION

End Class
