'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_EDO_MECANICO
    Public Property IDPOZO As String
    Public Property IDAGUJERO As String
    Public Property ETIQUETA As String
    Public Property NUMERO As Integer
    Public Property MD As Double
    Public Property TIDIAM As Nullable(Of Double)
    Public Property TIROUG As Nullable(Of Double)
    Public Property TODIAM As Nullable(Of Double)
    Public Property TOROUG As Nullable(Of Double)
    Public Property CIDIAM As Nullable(Of Double)
    Public Property CIROUG As Nullable(Of Double)

End Class
