'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_MOD_POZO
    Public Property IDMODPOZO As String
    Public Property IDAGUJERO As String
    Public Property IDPOZO As String
    Public Property FECHAMODELO As Nullable(Of Date)

End Class
