'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_TRAYECTORIA
    Public Property PROFUNDIDADMD As Double
    Public Property PROFMV As Nullable(Of Double)
    Public Property SEVERIDAD As Nullable(Of Double)
    Public Property IDAGUJERO As String
    Public Property IDPOZO As String

End Class
