'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_USUARIOS_POZOS
    Public Property POZO As String
    Public Property IDGERENCIA As String
    Public Property GERENCIA As String
    Public Property IDCOORDINACION As String
    Public Property COORDINACION As String
    Public Property IDDEPARTAMENTO As String
    Public Property DEPARTAMENTO As String
    Public Property IDCAMPO As String
    Public Property CAMPO As String
    Public Property IDPOZO As String
    Public Property USUARIO As String
    Public Property CONTRASENA As Byte()
    Public Property NOMBRE As String
    Public Property APELLIDOS As String
    Public Property IDUSUARIO As String

End Class
