'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_VLP_GASTOS
    Public Property IDMODPOZO As String
    Public Property PWFIPR As Double
    Public Property PWFVLP As Double
    Public Property TITULO As Nullable(Of Double)

End Class
